messages:
    back-valid: '&aTeleported to previous location.'
    back-invalid-no-locations: '&cYou have not teleported recently.'
    clone-valid: '&aItem cloned.'
    clone-invalid-item: '&cYou are not holding any item.'
    delete-warp-valid: '&aDeleted warp $warp.'
    delete-warp-usage: '&cUsage: /deletewarp [warp]'
    distance-invalid-untrackable: '&cThat player is not currently trackable.'
    distance-invalid-item: '&cYou require $amount x $type to use that command.'
    distance-invalid-distance: '&cYou are too far away to get the distance to that player.'
    distance-valid: '&aDistance to $character/$player: $distance'
    distance-untrackable-notification: '&c$player attempted to check their distance to you. If you wish for them to be able to find you, re-enable tracking with /toggletracking.'
    distance-invalid-world: '&cThat player is in a different world.'
    distance-invalid-player: '&cThere is no player by that name online.'
    distance-usage: '&cUsage: /distance [player]'
    enchant-valid: '&aSuccessfully enchanted $amount x $type with $enchantment $level'
    enchant-invalid-level: '&cThe enchantment level must be a number.'
    enchant-invalid-enchantment: '&cThere is no enchantment by that name.'
    enchant-invalid-illegal: '&cThat enchantment is illegal.'
    enchant-invalid-item: '&cYou must be holding something in order to enchant it.'
    enchant-usage: '&cUsage: /enchant [enchantment] [level]'
    feed-notification: '&aHunger refilled.'
    feed-valid: '&a$player''s hunger was refilled.'
    feed-usage-console: '&cWhen using this command from console, you must specify a player to feed.'
    fly-enable-notification: '&aFly mode enabled.'
    fly-enable-valid: '&aAllowed $player to fly.'
    fly-disable-notification: '&aFly mode disabled.'
    fly-disable-valid: '&aDisallowed $player to fly.'
    fly-usage-console: '&cWhen using this command from console, you must specify a player.'
    get-book-valid: '&aHere''s a book.'
    get-sign-valid: '&aHere''s a sign.'
    heal-notification: '&aHealed.'
    heal-valid: '&aHealed $player.'
    heal-usage-console: '&cWhen using this command from console, you must specify a player to heal.'
    inventory-valid: '&aViewing $player''s inventory.'
    inventory-invalid-player: '&cThere is no player by that name online.'
    inventory-usage: '&cUsage: /inventory [player]'
    item-invalid-amount: '&cThe amount must be an integer.'
    item-valid-plural: '&aCreated $amount $types.'
    item-valid-singular: '&aCreated a $type.'
    item-invalid-material: '&cCould not find a material by that name.'
    item-usage: '&cUsage: /item [type] [amount]'
    item-meta-set-name-valid: '&aSet item display name to $name.'
    item-meta-add-lore-valid: '&aAdded lore: "$lore&a".'
    item-meta-remove-lore-valid: '&cRemoved lore: "$lore&a".'
    item-meta-remove-lore-invalid-lore-item: '&cThat item does not have that piece of lore.'
    item-meta-remove-lore-invalid-lore: '&cThat item does not have any lore.'
    item-meta-usage: '&cUsage: /itemmeta [setname|addlore|removelore] [name|lore]'
    item-meta-invalid-item: '&cYou must be holding an item to modify its item meta.'
    jump-valid: '&aTeleported to first block in line of sight.'
    jump-invalid-block: '&cNo block was found within 64 blocks of your line of sight.'
    kit-valid: '&aClaimed $kit.'
    kit-invalid-kit: '&cThere is no kit by that name.'
    kit-list-title: '&fKit list:'
    kit-list-item: '&f- &7$kit'
    repair-valid: '&aItem repaired.'
    repair-invalid-item: '&cYou must be holding an item in order to repair it.'
    run-as-valid: '&aDispatched command.'
    run-as-invalid-player: '&cThere is no player by that name online.'
    run-as-usage: '&cUsage: /runas [player] [command]'
    seen-online: '&a$player is online now.'
    seen-date: '&a$player was last seen on $date at $time.'
    seen-diff: '&a(That''s $days days, $hours hours, $minutes minutes, $seconds seconds ago.)'
    seen-never: '&aThat player has never played on this server.'
    seen-usage: '&cUsage: /seen [player]'
    set-spawn-valid: '&aSpawn location of $world set.'
    set-warp-valid: '&aWarp $warp set in $world at $x, $y, $z'
    set-warp-usage: '&cUsage: /setwarp [name]'
    smite-usage: '&cUsage: /smite [player]'
    smite-invalid-player: '&cThere is no player by that name online.'
    smite-valid: '&aOpening the heavens on $player.'
    spawn-valid: '&aTeleported to spawn.'
    spawner-valid: '&aSpawner type set.'
    spawner-invalid-entity: '&cThere is no entity by that name.'
    spawner-invalid-block: '&cThat''s not a mob spawner.'
    spawner-usage: '&cUsage: /spawner [type]'
    spawn-mob-valid: '&aMobs spawned.'
    spawn-mob-invalid-amount: '&cThe amount of mobs must be an integer.'
    spawn-mob-invalid-mob: '&cThat entity type does not exist.'
    spawn-mob-usage: '&cUsage: /spawnmob [type] [amount]'
    speed-invalid-speed-number: '&cSpeed must be a number.'
    speed-reset-valid: '&aReset $player''s fly speed.'
    speed-reset-notification: '&aYour fly speed was reset by $player.'
    speed-set-valid: '&aSet $player''s fly speed to $speed.'
    speed-set-notification: '&aYour fly speed was set to $speed by $player.'
    speed-invalid-speed-bounds: '&cSpeed must be between -1.0 and 1.0'
    speed-usage-console: '&cWhen using this command from console, you must specify a player to change the fly speed of.'
    toggle-log-messages-valid: '&aLog messages $enabled.'
    toggle-tracking-on-valid: '&aYou have allowed people to find you with /track and /distance.'
    toggle-tracking-off-valid: '&aYou have disallowed people to find you with /track and /distance.'
    track-invalid-untrackable: '&cThat player is not currently trackable.'
    track-invalid-item: '&cYou require $amount x $type to use that command.'
    track-invalid-distance: '&cYou are too far away to track that player.'
    track-valid: '&aNow tracking $player/$character.'
    track-untrackable-notification: '&c$player attempted to track you. If you wish for them to be able to find you, re-enable tracking with /toggletracking.'
    track-invalid-player: '&cThere is no player by that name online.'
    track-usage: '&cUsage: /track [player]'
    unsign-valid: '&aBook unsigned.'
    unsign-invalid-book: '&cYou must be holding a written book to unsign.'
    warp-valid: '&aWarped to $warp.'
    warp-invalid-warp: '&cThere is no warp by that name.'
    warp-list-title: '&fWarps: '
    warp-list-item: '&7$warps'
    warp-list-invalid-empty: '&cNo warps are currently set. Set one using /setwarp [name].'
    no-permission-back: '&cYou do not have permission to go back.'
    no-permission-clone: '&cYou do not have permission to clone items.'
    no-permission-delete-warp: '&cYou do not have permission to delete warps.'
    no-permission-distance: '&cYou do not have permission to check your distance to players.'
    no-permission-enchant: '&cYou do not have permission to enchant items.'
    no-permission-feed: '&cYou do not have permission to feed players.'
    no-permission-fly: '&cYou do not have permission to toggle fly mode.'
    no-permission-get-book: '&cYou do not have permission to get books.'
    no-permission-get-sign: '&cYou do not have permission to get signs.'
    no-permission-heal: '&cYou do not have permission to heal players.'
    no-permission-inventory: '&cYou do not have permission to view other people''s inventories.'
    no-permission-item: '&cYou do not have permission to spawn items.'
    no-permission-item-meta: '&cYou do not have permission to modify item meta.'
    no-permission-jump: '&cYou do not have permission to jump.'
    no-permission-kit: '&cYou do not have permission to claim kits.'
    no-permission-repair: '&cYou do not have permission to repair items.'
    no-permission-run-as: '&cYou do not have permission to run commands as other players.'
    no-permission-seen: '&cYou do not have permission to see when players were last online.'
    no-permission-set-spawn: '&cYou do not have permission to set the spawn.'
    no-permission-set-warp: '&cYou do not have permission to set warps.'
    no-permission-smite: '&cYou do not have permission to smite people.'
    no-permission-spawn: '&cYou do not have permission to teleport to spawn.'
    no-permission-spawner: '&cYou do not have permission to change spawner types.'
    no-permission-spawn-mob: '&cYou do not have permission to spawn mobs.'
    no-permission-speed: '&cYou do not have permission to set fly speed.'
    no-permission-sudo: '&c$player is not in the sudoers file. This incident will be reported.'
    no-permission-toggle-log-messages: '&cYou do not have permission to toggle log messages.'
    no-permission-toggle-tracking: '&cYou do not have permission to toggle tracking.'
    no-permission-track: '&cYou do not have permission to track players.'
    no-permission-unsign: '&cYou do not have permission to unsign written books.'
    no-permission-warp: '&cYou do not have permission to warp.'
    not-from-console: '&cYou must be a player to perform this command.'
    no-character-self: '&cYou must have a character to perform that command.'
    no-character-other: '&cThat player must have a character to perform that command.'
distance-command:
    maximum-distance: 64000
    item-requirement:
        ==: org.bukkit.inventory.ItemStack
        type: COMPASS
track-command:
    maximum-distance: 1000
    item-requirement:
        ==: org.bukkit.inventory.ItemStack
        type: COMPASS
time-slow-factor: 4
daily-messages:
- '&7"That makes sense!"'
- '&7"You can always grind on a sheep!"'
- '&7"I am the best butt-kisser around!"'
- '&7"Dwarves are short!"'
- '&7"You probably think you''re ugly, but you''re actually pretty decent!"'
- '&7"Oh no... I must hide my stupidity!"'
- '&7"Dammit!"'
- '&7"Why stops me from quoting myself? Huh!?"'
- '&7"Oh shit, my thirst is 4!"'
- '&7"Train hard!"'
- '&7"Be excellent to each other. And... PARTY ON DUDES!"'
- '&7"Evil will always triumph over good because good is dumb."'
- '&7"There''s only two things I hate in this world. People who are intolerant of other people''s cultures and the Dwarves."'
- '&7"I''m sure that we can handle this situation maturely, just like the responsible adults that we are. Isn''t that right, Mr. Poopy Pants?"'
- '&7"The only thing we don''t have a god for is premature ejaculation but I hear that''s coming quickly."'
- '&7"I fart in your general direction. Your mother was a hamster and your father smelt of elderberries.  Now go away, or I shall taunt you a second time."'
- '&7"Time marches on and sooner or later you realize it is marching across your face."'
- '&7"Fat, drunk, and stupid is no way to go through life, son."'
- '&7"Listen, strange women lyin'' in ponds distributin'' swords is no basis for a system of government. Supreme executive power derives from a mandate from the masses, not from some farcical aquatic ceremony."'
- '&7"If she weighed the same as a duck... she''s made of wood. And therefore... a witch!'
- '&7"Look, you stupid Bastard. You''ve got no arms left."'
- '&7"Oh, but you can''t expect to wield supreme executive power just because some watery tart threw a sword at you."'
- '&7"We are now the Knights who say... "Ekki-Ekki-Ekki-Ekki-PTANG. Zoom-Boing. Z''nourrwringmm."'
- '&7"...and that, my liege, is how we know the Earth to be banana shaped."'
- '&7"This new learning amazes me, Sir Bedevere. Explain again how sheep''s bladders may be employed to prevent earthquakes."'
- '&7"That''s the most foul, cruel, and bad-tempered rodent you ever set eyes on!"'
- '&7"Oh, king eh? Very nice. And how''d you get that, eh? By exploiting the workers. By hanging on to outdated imperialist dogma which perpetuates the economic and social differences in our society."'
- '&7"I *warned* you, but did you listen to me? Oh, no, you *knew*, didn''t you? Oh, it''s just a harmless little *bunny*, isn''t it?"'
- '&7"Don''t like her? What''s wrong with her? She''s beautiful, she''s rich, she''s got huge... tracts of land."'
- '&7"You must spank her well, and after you are done with her, you may deal with her as you like... and then... spank me."'
- '&7"I''m not going to be a sexualised character unless I need to be to get things"'
- '&7"You gotta update your Linux drivers!"'
- '&7"I don''t know how Hitler lost World War 2, it''s so easy!"'
- '&7"Words piss me off!"'
- '&7"There must be more to the game than this! There''s doors but I can''t get through the doors."'
- '&7"We all just received large amounts of justice to our internal organs"'
- '&7"Everyone deserves a 60th chance"'
- '&7"Do they even know how to Ball Cam?"'
- '&7"How did he [Buddha] even find out about Nirvana anyway? They weren''t even a band until 1990!"'
- '&7"These Pok√©mon defy Minecraft logic!"'
- '&7"Kony? Wasn''t he a clown or something?"'
- '&7"I''m a pro terrorist: I''m both in favour of terrorists, and a good one."'
- '&7"You''re basically a Sven who can charge and screams ''Moo''!"'
- '&7"Believe in the dream."'
- '&7"It is not uncommon for things during Ludum Dare to just not work."'
- '&7"My pizzas are more processed than a word document."'
- '&7"All I hear is BAR BAR BAR."'
- '&7"Gonna get some banana cake! And ice cream! I''m a responsible adult, okay?"'
- '&7"Think how swag we could look, we could have the top dog edgies and the pleb edgies"'
- '&7"Back in my day..."'
- '&7"Licences are butts anyway."'
- '&7"You may not take credit for a stupid idea that somehow worked!"'
- '&7"I''ve always wanted to make a second fake tinder account, just to cat fish people"'
- '&7"Is Ulti really calling me retarded..."'
- '&7"I love legacy code"'
- '&7"I hate anime so much."'
- '&7"Can our family motto not be incest is wincest?"'
- '&7Mitchell: "Would you fuck a black person Tomi?" Tomi: *In a disgusted manner* "No."'
- '&7"At least I haven''t gotten into the quotes yet."'
- '&7"I fell asleep and I woke up on top of him."'
- '&7"I showed pictures to everyone."'
- '&7"That''s what physics is: using dumb models nobody understands to solve problems nobody cares about."'
kits:
- ==: com.rpkit.essentials.bukkit.kit.RPKKitImpl
  id: 1
  name: eggxample # "I take full credit" - LiamLime
  items:
  - ==: org.bukkit.inventory.ItemStack
    type: EGG