distance-command:
  maximum-distance: 64000
  item-requirement:
    ==: org.bukkit.inventory.ItemStack
    v: 3218
    type: COMPASS
track-command:
  maximum-distance: 1000
  item-requirement:
    ==: org.bukkit.inventory.ItemStack
    v: 3218
    type: COMPASS
daily-messages:
- '&7"Ye can''t crown a king with a bobble ''at"'
- '&7"Let me check my wocket potch"'
- '&7"Who built a wooden bridge over a lava?!"'
- '&7"Go back! I want to be Monkey!"'
- '&7"Luck be a lady, and she just so happens to be a lesbian"'
- '&7"Nace is my emotional support pyromancer"'
- '&7"Lord Cain Soren cracks his fingers. "Today. Aye shall play. Megalovania."'
- '&7"one simp, two simp, red tief, pink tief"'
- '&7"I have a stack of papers with plans to ruin just about everyone in this tavern."'
- '&7"Ze wolf was... big"'
- '&7"***INTENSE EATING SOUNDS***"'
- '&7"theres the two elven women havign [sic] a normal conversation, the water twink doing what the water twink does best, and two angry grumps having a battle to the death"'
- '&7"want to help us spin the mushroom god"'
- '&7"All have drink, toast to life suck, okay?"'
- '&7"Batsharks are just a child''s tale, Nace. Bats don''t exist."'

kits:
- ==: com.rpkit.essentials.bukkit.kit.RPKKitImpl
  id: 1
  name: eggxample # "I take full credit" - LiamLime
  items:
  - ==: org.bukkit.inventory.ItemStack
    v: 3218
    type: EGG
time:
  change-speed-enabled: true
  # Durations are ISO 8601 Period format: https://en.wikipedia.org/wiki/ISO_8601#Durations
  day-duration: PT3H
  night-duration: PT3H
caching:
  rpkit_log_messages_enabled:
    minecraft_profile_id:
      enabled: true
      size: 20
  rpkit_previous_location:
    minecraft_profile_id:
      enabled: true
      size: 20
  rpkit_tracking_enabled:
    id:
      enabled: true
      size: 20