warnings:
  3: "ban ${player} Reached 3 warnings"
caching:
  rpkit_ticket:
    id:
      enabled: true
      size: 20
  rpkit_vanish_state:
    id:
      enabled: true
      size: 20
  rpkit_warning:
    id:
      enabled: true
      size: 20