groups:
- &default
  ==: RPKGroupImpl
  name: default
  inheritance: []
  allow:
  - example.allow.permission
  deny:
  - example.deny.permission
- &et
  ==: RPKGroupImpl
  name: et
  inheritance: [*default]
  allow:
  - example.et.permission
  deny: []
- &dev
  ==: RPKGroupImpl
  name: dev
  inheritance: [*default]
  allow:
  - example.dev.permission
  deny: []
- &mod
  ==: RPKGroupImpl
  name: mod
  inheritance: [*default]
  allow:
  - example.mod.permission
  deny: []
- &admin
  ==: RPKGroupImpl
  name: admin
  inheritance: [*mod]
  allow:
  - example.admin.permission
  deny: []
default-group: *default