lock-item:
  ==: org.bukkit.inventory.ItemStack
  v: 3105
  type: IRON_INGOT
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: '{"extra":[{"text":"Lock"}],"text":""}'
    lore:
      - '{"extra":[{"text":"Used for locking chests"}],"text":""}'
key-item:
  ==: org.bukkit.inventory.ItemStack
  v: 3105
  type: IRON_INGOT
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: '{"extra":[{"text":"Key"}],"text":""}'
caching:
  rpkit_keyring:
    character_id:
      enabled: true
      size: 20
  rpkit_locked_block:
    block:
      enabled: true
      size: 100
  rpkit_player_getting_key:
    minecraft_profile_id:
      enabled: true
      size: 20
  rpkit_player_unclaiming:
    minecraft_profile_id:
      enabled: true
      size: 20
