# These are parsed as mathematical expressions. You may use variables added by other plugins.
# Built in variables are:
# character: The character (RPKCharacter)
# minecraftLevel: The player's level in Minecraft (Integer)
# characterGender: The character's gender from the character implementation (String)
# characterAge: The character's age from the character implementation (Integer)
# characterSpecies: The character's species from the character implementation (RPKSpecies)
# characterHelmet: The character's helmet from the character implementation (ItemStack)
# characterChestplate: The character's chestplate from the character implementation (ItemStack)
# characterLeggings: The character's leggings from the character implementation (ItemStack)
# characterBoots: The character's boots from the character implementation (ItemStack)
# characterHealth: The character's health from the character implementation (Double)
# characterMaxHealth: The character's max health from the character implementation (Double)
# characterMana: The character's mana from the character implementation (Integer)
# characterMaxMana: The character's max mana from the character implementation (Integer)
# characterFoodLevel: The character's food level from the character implementation (Integer)
# characterThirstLevel: The character's thirst level from the character implementation (Integer)
stats:
  strength: strength
  agility: agility
  intelligence: intelligence
